#ifndef CONSTANTS_H
#define CONSTANTS_H
#define DATETIME_FORMAT "yyyy-MM-dd HH:mm:ss"
#define TASK_STATUS_STARTED     1
#define TASK_STATUS_FINISHED    2
#define TASK_STATUS_CANCELED    3

#define TREEVIEW_TYPE_COLLECTION 1
#define TREEVIEW_TYPE_PROJECT 2
#define TREEVIEW_TYPE_YEAR 3
#define TREEVIEW_TYPE_MONTH 4
#define TREEVIEW_TYPE_DAY 5
#define TREEVIEW_TYPE_EVENT 6
#endif // CONSTANTS_H
