0|CREATE TABLE version(version INTEGER);
0|INSERT INTO version(version) VALUES(1);
0|CREATE TABLE collection(id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(64));
0|CREATE TABLE project(id INTEGER PRIMARY KEY AUTOINCREMENT, collection_id INTEGER REFERENCES collection (id) ON DELETE CASCADE ON UPDATE CASCADE, name VARCHAR(128), color VARCHAR(6));
0|CREATE TABLE task(id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER REFERENCES project(id) ON DELETE CASCADE ON UPDATE CASCADE, title VARCHAR(128), duedate DATETIME, content TEXT, status INTEGER);
