0|CREATE TABLE version(version INTEGER);
0|INSERT INTO version(version) VALUES(1);
0|CREATE TABLE collection(id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(64));
0|CREATE TABLE project(id INTEGER PRIMARY KEY AUTOINCREMENT, collection_id INTEGER REFERENCES collection (id) ON DELETE CASCADE ON UPDATE CASCADE, name VARCHAR(128), color VARCHAR(6));
0|CREATE TABLE task(id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER REFERENCES project(id) ON DELETE CASCADE ON UPDATE CASCADE, title VARCHAR(128), duedate DATETIME, content TEXT, status INTEGER);
0|CREATE TABLE event(id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER REFERENCES project(id) ON DELETE CASCADE ON UPDATE CASCADE, title VARCHAR(128), evedate DATETIME, content TEXT);
1|ALTER TABLE task ADD COLUMN priority INTEGER;
1|UPDATE task SET priority=0;
1|UPDATE version SET version=2;
